import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';
import { ProductModel } from '../models/product.model';
import { StoreModel } from '../models/store.model';
import { CategoryModel } from '../models/category.model';

@Injectable({ providedIn: 'root' })
export class StoreService {
  constructor(private _httpClient: HttpClient) {}

  getAllCategories(): Observable<CategoryModel[]> {
    return of([
      {
        name: 'Dairy, Bread & Eggs',
        imageUrl: '/assets/images/category/category-dairy-bread-eggs.jpg',
        id: '1',
      },
      {
        name: 'Snack & Munchies',
        imageUrl: '/assets/images/category/category-snack-munchies.jpg',
        id: '2',
      },
      {
        name: 'Bakery & Biscuits',
        imageUrl: '/assets/images/category/category-bakery-biscuits.jpg',
        id: '3',
      },
      {
        name: 'Tea, Coffee & Drinks',
        imageUrl: '/assets/images/category/category-tea-coffee-drinks.jpg',
        id: '4',
      },
      {
        name: 'Fruits & Vegetables',
        imageUrl: '/assets/images/category/category-fruits-vegetables.jpg',
        id: '5',
      },
      {
        name: 'Cold Drinks & Juices',
        imageUrl: '/assets/images/category/category-cold-drinks-juices.jpg',
        id: '6',
      },
      {
        name: 'Chicken, Meat & Fish',
        imageUrl: '/assets/images/category/category-chicken-meat-fish.jpg',
        id: '7',
      },
      {
        name: 'Instant Food',
        imageUrl: '/assets/images/category/category-instant-food.jpg',
        id: '8',
      },
    ]);
  }

  getAllStories(): Observable<StoreModel[]> {
    return of([
      {
        name: 'E-Grocery Super Market',
        logoUrl: '/assets/images/stores-logo/stores-logo-1.svg',
        distanceInMeters: 1277,
        tagIds: ['1', '2', '7'],
        id: '1',
      },
      {
        name: 'DealShare Mart',
        logoUrl: '/assets/images/stores-logo/stores-logo-2.svg',
        distanceInMeters: 2198,
        tagIds: [],
        id: '2',
      },
      {
        name: 'DMart',
        logoUrl: '/assets/images/stores-logo/stores-logo-3.svg',
        distanceInMeters: 851,
        tagIds: [],
        id: '3',
      },
      {
        name: 'Blinkit Store',
        logoUrl: '/assets/images/stores-logo/stores-logo-4.svg',
        distanceInMeters: 4238,
        tagIds: [],
        id: '4',
      },
      {
        name: 'StoreFront Super Market',
        logoUrl: '/assets/images/stores-logo/stores-logo-5.svg',
        distanceInMeters: 3075,
        tagIds: [],
        id: '5',
      },
      {
        name: 'BigBasket',
        logoUrl: '/assets/images/stores-logo/stores-logo-6.svg',
        distanceInMeters: 188,
        tagIds: [],
        id: '6',
      },
      {
        name: 'Swiggy Instamart',
        logoUrl: '/assets/images/stores-logo/stores-logo-7.svg',
        distanceInMeters: 76,
        tagIds: [],
        id: '7',
      },
      {
        name: 'Online Grocery Mart',
        logoUrl: '/assets/images/stores-logo/stores-logo-8.svg',
        distanceInMeters: 6625,
        tagIds: [],
        id: '8',
      },
      {
        name: 'Spencers',
        logoUrl: '/assets/images/stores-logo/stores-logo-9.svg',
        distanceInMeters: 532,
        tagIds: [],
        id: '9',
      },
    ]);
  }

  getAllProducts(): Observable<ProductModel[]> {
    return of([
      {
        name: 'Beatroot',
        price: 2,
        categoryId: '5',
        ratingValue: 2.7,
        ratingCount: 94,
        imageUrl: '/assets/images/products/product-img-19.jpg',
        featureValue: 5,
        storeIds: ['2'],
        id: '10',
      },
      {
        name: 'Fresh Bananas',
        price: 4,
        categoryId: '5',
        ratingValue: 4.3,
        ratingCount: 741,
        imageUrl: '/assets/images/products/product-img-18.jpg',
        featureValue: 6,
        storeIds: ['1', '2'],
        id: '9',
      },
      {
        name: 'Fresh Kiwi',
        price: 1,
        categoryId: '5',
        ratingValue: 3.9,
        ratingCount: 221,
        imageUrl: '/assets/images/products/product-img-17.jpg',
        featureValue: 7,
        storeIds: ['2'],
        id: '8',
      },
      {
        name: 'Golden Pineapple',
        price: 3,
        categoryId: '5',
        ratingValue: 4.9,
        ratingCount: 921,
        imageUrl: '/assets/images/products/product-img-16.jpg',
        featureValue: 8,
        storeIds: ['2'],
        id: '7',
      },
      {
        name: 'Fresh Apple',
        price: 2,
        categoryId: '5',
        ratingValue: 4.8,
        ratingCount: 1521,
        imageUrl: '/assets/images/products/product-img-15.jpg',
        featureValue: 9,
        storeIds: ['1', '2'],
        id: '6',
      },
      {
        name: 'Salted Instant Popcorn',
        price: 13,
        categoryId: '2',
        ratingValue: 2.5,
        ratingCount: 521,
        imageUrl: '/assets/images/products/product-img-5.jpg',
        featureValue: 6,
        storeIds: ['3'],
        id: '1',
      },
      {
        name: 'Onion Flavour Chips',
        price: 3,
        categoryId: '2',
        ratingValue: 3.5,
        ratingCount: 423,
        imageUrl: '/assets/images/products/product-img-4.jpg',
        featureValue: 7,
        storeIds: ['1'],
        id: '2',
      },
      {
        name: 'Cadbury 5 Star Chocolate',
        price: 14,
        categoryId: '2',
        ratingValue: 5,
        ratingCount: 25,
        imageUrl: '/assets/images/products/product-img-10.jpg',
        featureValue: 8,
        storeIds: ['1', '3'],
        id: '3',
      },
      {
        name: "Haldiram's Sev Bhujia",
        price: 18,
        categoryId: '2',
        ratingValue: 4.2,
        ratingCount: 149,
        imageUrl: '/assets/images/products/product-img-1.jpg',
        featureValue: 10,
        storeIds: ['1'],
        id: '4',
      },
      {
        name: 'Nutri Choice Digestive',
        price: 24,
        categoryId: '2',
        ratingValue: 4.9,
        ratingCount: 69,
        imageUrl: '/assets/images/products/product-img-2.jpg',
        featureValue: 9,
        storeIds: ['1'],
        id: '5',
      },
      {
        name: '5 star Bites',
        price: 44,
        categoryId: '2',
        ratingValue: 2.9,
        ratingCount: 62,
        imageUrl: '/assets/images/products/product-img-3.jpg',
        featureValue: 1,
        storeIds: ['2'],
        id: '11',
      },
      {
        name: 'Epigamia Green Yogurt',
        price: 31,
        categoryId: '2',
        ratingValue: 3.9,
        ratingCount: 19,
        imageUrl: '/assets/images/products/product-img-6.jpg',
        featureValue: 2,
        storeIds: ['1'],
        id: '12',
      },
      {
        name: 'Cheese Slices',
        price: 11,
        categoryId: '2',
        ratingValue: 3.2,
        ratingCount: 20,
        imageUrl: '/assets/images/products/product-img-7.jpg',
        featureValue: 1,
        storeIds: ['1', '2', '3'],
        id: '13',
      },
      {
        name: 'Corn Flakes',
        price: 61,
        categoryId: '2',
        ratingValue: 2.2,
        ratingCount: 29,
        imageUrl: '/assets/images/products/product-img-8.jpg',
        featureValue: 1,
        storeIds: ['1', '2'],
        id: '14',
      },
      {
        name: 'Millet Pancake',
        price: 75,
        categoryId: '2',
        ratingValue: 1.2,
        ratingCount: 121,
        imageUrl: '/assets/images/products/product-img-9.jpg',
        featureValue: 1,
        storeIds: ['1', '3'],
        id: '15',
      },
      {
        name: 'French Roast Coffee',
        price: 175,
        categoryId: '2',
        ratingValue: 2.2,
        ratingCount: 11,
        imageUrl: '/assets/images/products/product-img-11.jpg',
        featureValue: 1,
        storeIds: ['2', '3'],
        id: '16',
      },
      {
        name: 'Crushed Tomatoes',
        price: 15,
        categoryId: '2',
        ratingValue: 3.5,
        ratingCount: 110,
        imageUrl: '/assets/images/products/product-img-12.jpg',
        featureValue: 1,
        storeIds: ['1', '2'],
        id: '17',
      },
      {
        name: 'Nutty Chips',
        price: 55,
        categoryId: '2',
        ratingValue: 2.5,
        ratingCount: 112,
        imageUrl: '/assets/images/products/product-img-14.jpg',
        featureValue: 1,
        storeIds: ['3', '2'],
        id: '19',
      },
    ]);
  }
}
